# Basic Algebraic equations using variables
a=input("enter first number:  ")
b=input("enter second number: ")
a=int(a)
b=int(b)
print(a+b)
print(a-b)
print(a%b)
print(a**b)
print(a/b)
print(a*b)
print(a>b)
print(a<b)
print(a==b)
print(a!=b)
print(a!=a)
#Average of Two numbers:-)
a1 = input("give number: ")
a2=input("give another number: ")
a1=int(a1)
a2=int(a2)
print((a1+a2)//2)
a="harshal"
print(a[:7:])
print(len(a))
print(a.endswith("l"))
print(a.count("a"))
print(a.find("a"))
print(a.index("a"))
print(a.lower())
print(a.upper())
print(a.swapcase())
print(a.title())
print(a.isalnum())
print(a.capitalize())
print(a.replace("harshal","harshu"))
me="harshal started studying \t :-). \nshe is good in studies. \nshe will be going to rich very soon ."
print(me)
name=input()
print("Good Afternoon:-)", name)
letter = ('''          Dear <NAME>
          you are selected
          Date:<Date>''' )
NAME=input( "enter your name: ")
Date=input("enter your date: ")
letter = letter.replace( "<NAME>", NAME )
letter=letter.replace( "<Date>", Date )
print(letter)
# list slicing
fruits=input("enter 7 fruits ")
fruitslist=fruits.split(" ")
print(fruitslist)
Marks=input("Enter your Marks: ")
listmarks=Marks.split()
print(listmarks)
listmarks.sort()
print(listmarks)
